### ISSUE TITLE
PHP 8.0 Support

### ISSUE THREAD

**Issue by jmalloc** [recoilphp/recoil#168]
- [x] Blocked by https://github.com/eloquent/phony/issues/250
- [x] Blocked by https://github.com/recoilphp/api/issues/11 (fixed in [v1.0.2](https://github.com/recoilphp/api/releases/tag/1.0.2))
- [x] Blocked by https://github.com/recoilphp/kernel/issues/8 (fixed in [v1.0.5](https://github.com/recoilphp/kernel/releases/tag/1.0.5))
- [x] Blocked by https://github.com/recoilphp/dev/issues/20 (fixed in [v0.4.1](https://github.com/recoilphp/dev/releases/tag/0.4.1))
- [x] Blocked by https://github.com/recoilphp/react/issues/11 (fixed in [v1.0.3](https://github.com/recoilphp/react/releases/tag/1.0.3))

**Comment by samier** [comment]
@jmalloc any plan to upgrade to php 8? we are using https://github.com/signalwire/signalwire-php in one of the project, we are block by this issue and not able to upgrade our php version to 8, can you pls share you plan to upgrade it ?

**Comment by jmalloc** [comment]
Apologies for my late response.  I will try to allocate some time to this in the next couple of days.

FWIW, Recoil is working under PHP v8.  Each repo has a `php-8` branch that you can use, and I would appreciate any feedback.

The issue is that the test framework I'd been using (peridot) does not support PHP 8 (at least last time I checked), so I intend to port the tests to PHPUnit.

**Comment by jmalloc** [comment]
I haven't forgotten about this!  A lot of the blockers here mentioning moving away from Peridot towards PHPUnit for unit testing, but I simply don't have time to dedicate to doing that properly right now.

I'm forking [Peridot](https://github.com/peridot-php/peridot) and [Leo](https://github.com/peridot-php/leo) to the `recoilphp` organisation to get them working in PHP 8. Both these projects seem to be unmaintained, but in the shorter term this will at least offer me the ability to run the Recoil test suites under PHP 8 and the confidence to say it works properly.

**Comment by ttodua** [comment]
any news? we cant install this on PHP 8+
```
    - recoil/kernel is locked to version 1.0.3 and an update of this package was not requested.
    - recoil/kernel 1.0.3 requires php ^7.1 -> your php version (8.0.13) does not satisfy that requirement.
```

**Comment by jmalloc** [comment]
I've been trying to get through as much of these test changes as I can today.

I have just released `recoil/kernel` [v1.0.5](https://github.com/recoilphp/kernel/releases/tag/1.0.5) with PHP 8+ support, next is `recoil/dev` then I can finally update this repo and `recoil/react` (the useful bits).

Again, I can only apologise for how long this is taking me to update.

**Comment by jmalloc** [comment]
All projects in this organisation now have releases that build successfully under PHP v7.4, v8.0 and 8.1.

|  package                                                |  PHP 8+ support as of                                            |
|---------------------------------------------------------|------------------------------------------------------------------|
| [recoil/api](https://github.com/recoilphp/api)          | [v1.0.2](https://github.com/recoilphp/api/releases/tag/1.0.2)    |
| [recoilphp/kernel](https://github.com/recoilphp/kernel) | [v1.0.5](https://github.com/recoilphp/kernel/releases/tag/1.0.5) |
| [recoilphp/dev](https://github.com/recoilphp/dev)       | [v0.4.1](https://github.com/recoilphp/dev/releases/tag/0.4.1)    |
| [recoilphp/react](https://github.com/recoilphp/react)   | [v1.0.3](https://github.com/recoilphp/react/releases/tag/1.0.3)  |
| [recoilphp/react](https://github.com/recoilphp/recoil)  | [v1.0.2](https://github.com/recoilphp/recoil/releases/tag/1.0.2) |

Very few changes to production code were made in any of these versions, it was largely a housekeeping exercise that involved making forks of the following (abandoned?) projects to add PHP 8 support (or at least fix major issues):

- `peridot-php/leo`
- `peridot-php/peridot`
- `peridot-php/peridot-code-coverage-reporters`

I would have preferred to migrate all of the projects to use PHPUnit (some have been). On the off chance that anyone other than myself is using Peridot and the peridot plugin in `recoil/dev` I would urge you to find another solution for testing - and to let me know what works well!

Lastly, I thought it was worth mentioning that despite my lack of time for these projects at the moment I don't have any immediate plans to cease maintenance altogether. I consider Recoil itself to be feature complete and stable, and it does see continued use in production with my employer, although I myself am no longer working with PHP.  Longer term I hope that the addition of "fibers" to PHP and perhaps first-class coroutine support in ReactPHP will render Recoil obsolete!

Thanks again to everyone for your patience. If there are any further issues surrounding usage under PHP 8, please open new issues for specific problems :)

**Comment by ttodua** [comment]
Thanks @jmalloc for the hard work you did ! As it is also in your goals now, I hope _your hope_ will come true and ReactPhp will be able do these things.

**Comment by edolix** [comment]
You rock, @jmalloc ! Thanks for your hard work!

**Comment by ttodua** [comment]
@jmalloc can you please mention, did ReactPHP made any step forward to what you referred as _first-class support for coroutines_?

**Comment by jmalloc** [comment]
This is all I'm aware of https://github.com/reactphp/async/tree/ed23203dfc9f60c5d16e4eb06e39e4248ec3c59b#coroutine.

**Comment by ttodua** [comment]
@jmalloc seems there was this too, if you know or not: https://clue.engineering/2022/announcing-reactphp-async
